<?php
/**
 * @file
 * Code for the Drupal.hu multi-index kereső feature.
 */

include_once 'drupalhu_multi_index_search.features.inc';

/**
 * Implements hook_form_FORM_ID_alter().
 */
function drupalhu_multi_index_search_form_views_exposed_form_alter(&$form, &$form_state) {
  if ($form['#id'] == 'views-exposed-form-multi-index-kereso-page-kereso') {
    $form['text']['#size'] = 20;
    $form['submit']['#value'] = 'Keresés';
  }
}
