_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
langcode: hu
module:
  acquia_connector: 0
  acquia_search: 0
  admin_toolbar: 0
  admin_toolbar_tools: 0
  aggregator: 0
  allowed_formats: 0
  app_book: 0
  app_core: 0
  big_pipe: 0
  block: 0
  block_content: 0
  book: 0
  breakpoint: 0
  ckeditor5: 0
  comment: 0
  config: 0
  contact: 0
  contextual: 0
  crop: 0
  ctools: 0
  datetime: 0
  datetime_range: 0
  dynamic_page_cache: 0
  editor: 0
  entity_legal: 0
  facets: 0
  facets_block: 0
  facets_summary: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  history: 0
  honeypot: 0
  image: 0
  image_widget_crop: 0
  imageapi_optimize: 0
  language: 0
  layout_builder: 0
  layout_discovery: 0
  link: 0
  locale: 0
  media: 0
  media_library: 0
  menu_ui: 0
  node: 0
  options: 0
  override_node_options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  rabbit_hole: 0
  responsive_image: 0
  rh_node: 0
  rh_taxonomy: 0
  search_api: 0
  search_api_solr: 0
  string_field_formatter: 0
  svg_image: 0
  svg_image_responsive: 0
  system: 0
  taxonomy: 0
  telephone: 0
  text: 0
  token: 0
  toolbar: 0
  transliterate_filenames: 0
  user: 0
  webp: 0
  forum: 1
  menu_link_content: 1
  pathauto: 1
  views: 10
  appp: 1000
theme:
  claro: 0
  appb: 1
  appf: 1
  olivero: 0
profile: appp
