block:
  active:
    limit: 5
  new:
    limit: 5
topics:
  hot_threshold: 15
  order: 1
  page_limit: 25
vocabulary: forums
_core:
  default_config_hash: QIfZpz4g6BfEIyiL-WtauNYu31M8o3LvYlZ0VGRQtNo
langcode: hu
