unprotected_forms:
  - user_login_form
  - search_form
  - search_block_form
  - views_exposed_form
  - honeypot_settings_form
protect_all_forms: false
log: false
element_name: gender
time_limit: 3
expire: 300
form_settings:
  user_register_form: true
  user_pass: true
  contact_message_personal_form: false
  contact_message_site_admin_form: true
  node_book_form: false
  node_casestudy_form: false
  node_event_form: false
  node_forum_form: false
  node_job_form: false
  node_news_form: false
  node_note_form: false
  node_page_form: false
  comment_admin_form: false
  comment_comment_forum_form: false
_core:
  default_config_hash: 9bVDfWSa_In6VzTXmy04jJ_3ZQobihKjO9isuuUCPaw
langcode: hu
