message: '@site jelenleg karbantartás alatt áll, tartalma hamarosan újra elérhető lesz. Addig is köszönjük a türelmet.'
langcode: hu
_core:
  default_config_hash: Z5MXifrF77GEAgx0GQ6iWT8wStjFuY8BD9OruofWTJ8
