_core:
  default_config_hash: V9UurX2GPT05NWKG9f2GWQqFG2TRG8vczidwjpy7Woo
langcode: hu
first_day: 0
country:
  default: HU
timezone:
  default: Europe/Budapest
  user:
    configurable: true
    default: 0
    warn: false
