_core:
  default_config_hash: yXadRE77Va-G6dxhd2kPYapAvbnSvTF6hO4oXiOEynI
langcode: hu
uuid: ac6dae37-ab30-4ab1-bb3d-8d0422f96f89
name: Drupal.hu
mail: webmester@drupal.hu
slogan: ''
page:
  403: ''
  404: ''
  front: /hir
admin_compact_mode: false
weight_select_max: 100
default_langcode: hu
mail_notification: ''
