<?php

/**
 * @file
 * App functions.
 */

use Drupal\Core\Entity\EntityTypeInterface;

/**
 * Implements hook_entity_base_field_info_alter().
 */
function app_core_entity_base_field_info_alter(&$fields, EntityTypeInterface $entity_type) {
  /** @var \Drupal\Core\Field\BaseFieldDefinition[] $fields */
  if ($entity_type->id() === 'node') {
    if (isset($fields['title'])) {
      //$fields['title']->setDisplayConfigurable('view', TRUE);
      //$fields['title']->setLabel('Title');
    }
  }
}
