<?php

function about_page_install_tasks() {
  return array(
    'about_page_add_taxonomy_terms' => array(),
  );
}

function about_page_add_taxonomy_terms() {
  about_page_save_terms(
    'audience',
    array(
      'Contributors',
      'Designers/themers',
      'Programmers',
      'Site administrators',
      'Site builders',
      'Site users',
    )
  );
  about_page_save_terms(
    'level',
    array(
      'Beginner',
      'Intermediate',
      'Advanced',
    )
  );
}