<?php

/**
 * @file
 * Custom theme.
 */

/**
 * Implements template_preprocess_field().
 */
function dhuf_preprocess_field(&$vars) {
  if ($vars['field_type'] === 'entity_reference_revisions') {
    foreach ($vars['items'] as &$item) {
      if (!isset($item['attributes']['class'])) {
        $item['attributes']['class'] = [];
      }

      $item['attributes']['class'][] = 'clearfix';
    }
  }
}
