<?php
/**
 * Implements hook_init().
 * Intercepts certain requests and attempts to hotlink/download the remote
 * version.
 */
function stage_file_proxy_init() {

  // Make sure we're requesting a file in the files dir
  // Currently this only works for PUBLIC files
  $file_dir = _stage_file_proxy_file_dir();
  if (strpos($_GET['q'], $file_dir) !== 0) {
    return;
  }

  $relative_path = drupal_substr($_GET['q'], drupal_strlen($file_dir) + 1);

  // get origin server
  $server = variable_get('stage_file_proxy_origin', NULL);

  if ($server) {
    // is this an imagecache request? if so, request only the root file and let imagecache handle resizing
    if (variable_get('stage_file_proxy_use_imagecache_root', TRUE) && $original_path = _stage_file_proxy_image_style_path_original($relative_path, TRUE)) {
      $relative_path = $original_path;
      if (file_exists($file_dir . '/' . $relative_path)) {
        return; // imagecache can generate it without our help.
      }
    }

    if (variable_get('stage_file_proxy_hotlink', FALSE)) {
      header("Location: $server/{$_GET['q']}");
      exit;
    }
    elseif (_stage_file_proxy_fetch($server, $relative_path)) {
      // Just refresh this request and let the web server work out the mime type, etc.
      header("Location: /{$_GET['q']}");
      exit;
    }
    else {
      watchdog(WATCHDOG_ERROR, 'Stage File Proxy encountered an unknown error');
      drupal_not_found();
      exit;
    }
  }
}

function _stage_file_proxy_fetch($server, $relative_path) {
  $dirs = explode('/', $relative_path);
  $filename = array_pop($dirs);
  $tree = array();
  $file_dir = _stage_file_proxy_file_dir();
  $dir_path = $file_dir;
  foreach ($dirs as $dir) {
    $tree[] = $dir;
    $dir_path = $file_dir . '/' . implode('/', $tree);
    if (!is_dir($dir_path)) {
      mkdir($dir_path);
    }
  }
  $url = $server . '/' . $dir_path . '/' . rawurlencode($filename);
  $ch = curl_init($url);
  curl_setopt($ch, CURLOPT_RETURNTRANSFER, TRUE);
  curl_setopt($ch, CURLOPT_FOLLOWLOCATION, TRUE);
  curl_setopt($ch, CURLOPT_USERAGENT, 'Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.8.1.15) Gecko/20080623 Firefox/2.0.0.15');
  $res = curl_exec($ch);
  if (curl_getinfo($ch, CURLINFO_HTTP_CODE) < 300) {
    file_put_contents($file_dir . '/' . $relative_path, $res);
    return TRUE;
  }
  return FALSE;
}

/**
 * Helper to retrieve the file directory
 */
function _stage_file_proxy_file_dir() {
  return variable_get('file_public_path', conf_path() . '/files');
}

/**
 * Helper to retrieves original path for a styled image.
 *
 * @param string $uri
 *   a uri or path (may be prefixed with scheme)
 * @param bool $style_only
 *   indicates if, the function should only return paths retrieved from style
 *   paths. Defaults to TRUE.
 * @return
 *   a path to the given original image
 *   if $style_only is set to TRUE and $uri is no style-path, FALSE is returned.
 */
function _stage_file_proxy_image_style_path_original($uri, $style_only = TRUE) {
  $scheme = file_uri_scheme($uri);
  if ($scheme) {
    $path = file_uri_target($uri);
  }
  else {
    $path = $uri;
    $scheme = file_default_scheme();
  }

  // It is a styles path, so we extract the different parts.
  if (strpos($path, 'styles') === 0) {
    // then the path is like styles/[style_name]/[schema]/[original_path]
    return preg_replace('/styles\/.*\/.*\/(.*)/U', '$1', $path);
  }
  // else it seems to be the original.
  elseif ($style_only == FALSE) {
    return $path;
  }
  else {
    return FALSE;
  }
}
