<?php
/**
 * @file
 * Basic functions for Drupal.hu.
 */

/**
 * Implements hook_preprocess_views_view().
 */
function dhu_preprocess_views_view(&$vars) {
  if ((($vars['name'] == 'dhu_search') && ($vars['display_id'] == 'page'))
    || (($vars['name'] == 'dhu_search_comment') && ($vars['display_id'] == 'page'))
  ) {
    $vars['header'] = render(views_block_view('-exp-' . $vars['name'] . '-' . $vars['display_id']));
  }
}

/**
 * Implements hook_preprocess().
 */
function dhu_preprocess_links(array &$variables) {
  static $destination;

  if (isset($variables['attributes']['id']) && 'secondary-menu-links' == $variables['attributes']['id']) {
    if (empty($destination)) {
      $destination = drupal_get_destination();
    }

    if (isset($variables['links'])) {
      foreach ($variables['links'] as $menu_name => $link) {
        switch ($link['href']) {
          case 'user/logout':
          case 'user/login':
            $variables['links'][$menu_name]['query'] = $destination;
            break;

        }
      }
    }
  }
}

/**
 * Implements hook_system_info_alter().
 */
function dhu_system_info_alter(&$info, $file, $type) {
  $path = pathinfo($file->filename, PATHINFO_DIRNAME);
  if (_dhu_is_custom_extension($path)) {
    $info['interface translation project'] = FALSE;
  }
}

/**
 * Implements hook_update_projects_alter().
 */
function dhu_update_projects_alter(&$projects) {
  foreach (array_keys($projects) as $project_name) {
    if (_dhu_is_custom_project($projects[$project_name])) {
      unset($projects[$project_name]);
    }
  }
}

/**
 * @param array $project
 *
 * @return bool
 */
function _dhu_is_custom_project(array $project) {
  $non_regular_names = array(
    'geocode',
    'vote_up_down',
    'konyvlap_cimkek',
  );

  return (
    preg_match('/^(dhu|drupalhu)/', $project['name'])
    || in_array($project['name'], $non_regular_names)
  );
}

/**
 * @param string $path
 *   File system path to a directory.
 *
 * @return bool
 *   Return TRUE if the $path directory contains custom module or theme.
 */
function _dhu_is_custom_extension($path) {
  $pattern = '@^sites/all/(modules/(custom|features))|(themes/(?!(bootstrap|omega|zen)))/@';

  return (bool) preg_match($pattern, $path);
}
